language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.10"

# command to install dependencies
install: "pip install six coveralls"
# command to run tests
script: coverage run --source=extend_me.py extend_me.py -v

after_success:
  coveralls

