language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
# command to install dependencies
install: "pip install six coveralls"
# command to run tests
script: coverage run extend_me.py -v

after_success:
  coveralls

